<a href="https://colab.research.google.com/github/marioguerrerosalah/ANALITICA-DE-NEGOCIOS/blob/main/Clase_12_anallitica_de_negocios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow as tf
### Tensor flow me permite usar las caracteristicas de las redes neuronales de tensor flow-google
import keras
### Libreria de paquetes que me permite programar la red neuronal que quiero
from keras.models import Sequential
### Esta es el modelo de activacion de capas en secuencia
from keras.layers import Dense
### Esto me permite densificar la capa de la red nuronal
### Es decir cuantas neuronas quiero en cada capa

In [ ]:
### Montar la base de datos
ruta='/content/Base de datos esg.xlsx'
base=pd.read_excel(ruta)
base.head()


base2=base.dropna()
base2.columns

Index(['Empresa', 'Pais', 'Sector', 'ESG Score ', 'Environmental Score ',
       'Social Score ', 'Governance Score ', 'Board Gender Diversity ',
       'Board Gender Diversity Score ', 'Policy Board Diversity ',
       'CEO Board Member ', 'Beta ', 'WACC ', 'Size'],
      dtype='object')

In [ ]:
### Preparacion de los datos
y=base2[['ESG Score ']]
x=base2[['Environmental Score ','Social Score ', 'Governance Score ',
         'Board Gender Diversity Score ','CEO Board Member ', 'Beta ', 'WACC ']]

s_scaler=StandardScaler()
y_s=s_scaler.fit_transform(y)
x_s=s_scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x_s,y_s,train_size=.80,random_state=42)

In [ ]:
##Vamos a montar el modelo adaline para predecir ESG score a partir de las variables en x

modelA=Sequential()
modelA.add(Dense(1,activation='linear', input_dim=7,use_bias=False))##
modelA.compile(loss='mean_squared_error',optimizer='adam')
historyA=modelA.fit(x_train,y_train,epochs=150,batch_size=32)
ypA=modelA.predict(x_test)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.8049  
Epoch 2/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.8492 
Epoch 3/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.7807 
Epoch 4/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.7906 
Epoch 5/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4100 
Epoch 6/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5150 
Epoch 7/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.4106 
Epoch 8/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3378  
Epoch 9/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.4560 
Epoch 10/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4214 
Epoch 11/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.3171 
Epoch 12/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.3345 
Epoch 13/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1585 
Epoch 14/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.2087 
Epoch 15/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1163 
Epoch 16/150
9/9

In [ ]:
###Voy a hacer graficas para ver como se comporto el modelo

##Grafica de dispersión
plt.figure()
plt.scatter(y_test,ypA)
plt.xlabel('y_test')
plt.ylabel('ypA')
plt.show()

##Grafica de distribucion
plt.figure()
sns.displot((y_test.flatten(),ypA.flatten()),kde=True)
plt.xlabel('y_test')
plt.ylabel('ypA')
plt.show()

##correlación
print(np.corrcoef(y_test.flatten(),ypA.flatten()))

[[1.         0.97706551]
 [0.97706551 1.        ]]


In [ ]:
### Voy a buscar los pesos del modelo
wA=modelA.layers[0].get_weights()[0]
wA

array([[ 0.49104196],
       [ 0.32378525],
       [ 0.37312794],
       [-0.06064123],
       [ 0.0426497 ],
       [ 0.02699383],
       [-0.05170338]], dtype=float32)

In [ ]:
##Voy a montar el modelo MADALINE multiples capas multiples neuronas

modelM=Sequential()
modelM.add(Dense(4,activation='linear', input_dim=7,use_bias=False))
modelM.add(Dense(1,activation='relu',use_bias=False))
modelM.compile(loss='mean_squared_error',optimizer='adam')
historyM=modelM.fit(x_train,y_train,epochs=150,batch_size=32)
ypM=modelM.predict(x_test)

Epoch 1/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.2045  
Epoch 2/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.1194 
Epoch 3/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.8949  
Epoch 4/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.8596 
Epoch 5/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.8026 
Epoch 6/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.2548 
Epoch 7/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0649 
Epoch 8/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4236 
Epoch 9/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.7618 
Epoch 10/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.2372 
Epoch 11/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.9529 
Epoch 12/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6604 
Epoch 13/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.9365 
Epoch 14/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.6627 
Epoch 15/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9839 
Epoch 16/150
9/9 

1/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


In [ ]:
## ver los pesos

w0M=modelM.layers[0].get_weights()[0]
w1M=modelM.layers[1].get_weights()[0]
w0M,w1M
wtM=np.dot(w0M,w1M)
wtM
#

array([[ 0.4125508 ],
       [ 0.46929348],
       [ 0.26024425],
       [ 0.01163341],
       [-0.00490275],
       [-0.00854734],
       [-0.00629538]], dtype=float32)